<?php
/**
 * Auto-generated class. SQL syntax highlighting
 * 
 * Based on SQL-99 
 *
 * PHP version 4 and 5
 *
 * LICENSE: This source file is subject to version 3.0 of the PHP license
 * that is available through the world-wide-web at the following URI:
 * http://www.php.net/license/3_0.txt.  If you did not receive a copy of
 * the PHP License and are unable to obtain it through the web, please
 * send a note to license@php.net so we can mail you a copy immediately.
 *
 * @copyright  2004 Andrey Demenev
 * @license    http://www.php.net/license/3_0.txt  PHP License
 * @link       http://pear.php.net/package/Text_Highlighter
 * @category   Text
 * @package    Text_Highlighter
 * @author Andrey Demenev <demenev@on-line.jar.ru>
 *
 */

/**
 * @ignore
 */

/**
 * Auto-generated class. SQL syntax highlighting
 *
 * @author Andrey Demenev <demenev@on-line.jar.ru>
 * @category   Text
 * @package    Text_Highlighter
 * @copyright  2004 Andrey Demenev
 * @license    http://www.php.net/license/3_0.txt  PHP License
 * @version    Release: @package_version@
 * @link       http://pear.php.net/package/Text_Highlighter
 */
class  Text_Highlighter_SQL extends Text_Highlighter
{    /**
     * PHP4 Compatible Constructor
     *
     * @param array  $options
     * @access public
     */
    function Text_Highlighter_SQL($options=array())
    {
        $this->__construct($options);
    }


    /**
     *  Constructor
     *
     * @param array  $options
     * @access public
     */
    function __construct($options=array())
    {
        $this->_syntax = array (
            'keywords' => 
            array (
                'reserved' => 
                array (
                    'name' => 'reserved',
                    'innerGroup' => 'reserved',
                    'case' => false,
                    'inherits' => 'identifier',
                    'match' => 
                    array (
                        'absolute' => true,
                        'action' => true,
                        'add' => true,
                        'admin' => true,
                        'after' => true,
                        'aggregate' => true,
                        'alias' => true,
                        'all' => true,
                        'allocate' => true,
                        'alter' => true,
                        'and' => true,
                        'any' => true,
                        'are' => true,
                        'array' => true,
                        'as' => true,
                        'asc' => true,
                        'assertion' => true,
                        'at' => true,
                        'authorization' => true,
                        'before' => true,
                        'begin' => true,
                        'binary' => true,
                        'bit' => true,
                        'blob' => true,
                        'boolean' => true,
                        'both' => true,
                        'breadth' => true,
                        'by' => true,
                        'call' => true,
                        'cascade' => true,
                        'cascaded' => true,
                        'case' => true,
                        'cast' => true,
                        'catalog' => true,
                        'char' => true,
                        'character' => true,
                        'check' => true,
                        'class' => true,
                        'clob' => true,
                        'close' => true,
                        'collate' => true,
                        'collation' => true,
                        'column' => true,
                        'commit' => true,
                        'completion' => true,
                        'connect' => true,
                        'connection' => true,
                        'constraint' => true,
                        'constraints' => true,
                        'constructor' => true,
                        'continue' => true,
                        'corresponding' => true,
                        'create' => true,
                        'cross' => true,
                        'cube' => true,
                        'current' => true,
                        'current_date' => true,
                        'current_path' => true,
                        'current_role' => true,
                        'current_time' => true,
                        'current_timestamp' => true,
                        'current_user' => true,
                        'cursor' => true,
                        'cycle' => true,
                        'data' => true,
                        'date' => true,
                        'day' => true,
                        'deallocate' => true,
                        'dec' => true,
                        'decimal' => true,
                        'declare' => true,
                        'default' => true,
                        'deferrable' => true,
                        'deferred' => true,
                        'delete' => true,
                        'depth' => true,
                        'deref' => true,
                        'desc' => true,
                        'describe' => true,
                        'descriptor' => true,
                        'destroy' => true,
                        'destructor' => true,
                        'deterministic' => true,
                        'diagnostics' => true,
                        'dictionary' => true,
                        'disconnect' => true,
                        'distinct' => true,
                        'domain' => true,
                        'double' => true,
                        'drop' => true,
                        'dynamic' => true,
                        'each' => true,
                        'else' => true,
                        'end' => true,
                        'end-exec' => true,
                        'equals' => true,
                        'escape' => true,
                        'every' => true,
                        'except' => true,
                        'exception' => true,
                        'exec' => true,
                        'execute' => true,
                        'external' => true,
                        'false' => true,
                        'fetch' => true,
                        'first' => true,
                        'float' => true,
                        'for' => true,
                        'foreign' => true,
                        'found' => true,
                        'free' => true,
                        'from' => true,
                        'full' => true,
                        'function' => true,
                        'general' => true,
                        'get' => true,
                        'global' => true,
                        'go' => true,
                        'goto' => true,
                        'grant' => true,
                        'group' => true,
                        'grouping' => true,
                        'having' => true,
                        'host' => true,
                        'hour' => true,
                        'identity' => true,
                        'ignore' => true,
                        'immediate' => true,
                        'in' => true,
                        'indicator' => true,
                        'initialize' => true,
                        'initially' => true,
                        'inner' => true,
                        'inout' => true,
                        'input' => true,
                        'insert' => true,
                        'int' => true,
                        'integer' => true,
                        'intersect' => true,
                        'interval' => true,
                        'into' => true,
                        'is' => true,
                        'isolation' => true,
                        'iterate' => true,
                        'join' => true,
                        'key' => true,
                        'language' => true,
                        'large' => true,
                        'last' => true,
                        'lateral' => true,
                        'leading' => true,
                        'left' => true,
                        'less' => true,
                        'level' => true,
                        'like' => true,
                        'limit' => true,
                        'local' => true,
                        'localtime' => true,
                        'localtimestamp' => true,
                        'locator' => true,
                        'map' => true,
                        'match' => true,
                        'minute' => true,
                        'modifies' => true,
                        'modify' => true,
                        'module' => true,
                        'month' => true,
                        'names' => true,
                        'national' => true,
                        'natural' => true,
                        'nchar' => true,
                        'nclob' => true,
                        'new' => true,
                        'next' => true,
                        'no' => true,
                        'none' => true,
                        'not' => true,
                        'null' => true,
                        'numeric' => true,
                        'object' => true,
                        'of' => true,
                        'off' => true,
                        'old' => true,
                        'on' => true,
                        'only' => true,
                        'open' => true,
                        'operation' => true,
                        'option' => true,
                        'or' => true,
                        'order' => true,
                        'ordinality' => true,
                        'out' => true,
                        'outer' => true,
                        'output' => true,
                        'pad' => true,
                        'parameter' => true,
                        'parameters' => true,
                        'partial' => true,
                        'path' => true,
                        'postfix' => true,
                        'precision' => true,
                        'prefix' => true,
                        'preorder' => true,
                        'prepare' => true,
                        'preserve' => true,
                        'primary' => true,
                        'prior' => true,
                        'privileges' => true,
                        'procedure' => true,
                        'public' => true,
                        'read' => true,
                        'reads' => true,
                        'real' => true,
                        'recursive' => true,
                        'ref' => true,
                        'references' => true,
                        'referencing' => true,
                        'relative' => true,
                        'restrict' => true,
                        'result' => true,
                        'return' => true,
                        'returns' => true,
                        'revoke' => true,
                        'right' => true,
                        'role' => true,
                        'rollback' => true,
                        'rollup' => true,
                        'routine' => true,
                        'row' => true,
                        'rows' => true,
                        'savepoint' => true,
                        'schema' => true,
                        'scope' => true,
                        'scroll' => true,
                        'search' => true,
                        'second' => true,
                        'section' => true,
                        'select' => true,
                        'sequence' => true,
                        'session' => true,
                        'session_user' => true,
                        'set' => true,
                        'sets' => true,
                        'size' => true,
                        'smallint' => true,
                        'some' => true,
                        'space' => true,
                        'specific' => true,
                        'specifictype' => true,
                        'sql' => true,
                        'sqlexception' => true,
                        'sqlstate' => true,
                        'sqlwarning' => true,
                        'start' => true,
                        'state' => true,
                        'statement' => true,
                        'static' => true,
                        'structure' => true,
                        'system_user' => true,
                        'table' => true,
                        'temporary' => true,
                        'terminate' => true,
                        'than' => true,
                        'then' => true,
                        'time' => true,
                        'timestamp' => true,
                        'timezone_hour' => true,
                        'timezone_minute' => true,
                        'to' => true,
                        'trailing' => true,
                        'transaction' => true,
                        'translation' => true,
                        'treat' => true,
                        'trigger' => true,
                        'true' => true,
                        'under' => true,
                        'union' => true,
                        'unique' => true,
                        'unknown' => true,
                        'unnest' => true,
                        'update' => true,
                        'usage' => true,
                        'user' => true,
                        'using' => true,
                        'value' => true,
                        'values' => true,
                        'varchar' => true,
                        'variable' => true,
                        'varying' => true,
                        'view' => true,
                        'when' => true,
                        'whenever' => true,
                        'where' => true,
                        'with' => true,
                        'without' => true,
                        'work' => true,
                        'write' => true,
                        'year' => true,
                        'zone' => true,
                    ),
                ),
                'keyword' => 
                array (
                    'name' => 'keyword',
                    'innerGroup' => 'var',
                    'case' => false,
                    'inherits' => 'identifier',
                    'match' => 
                    array (
                        'abs' => true,
                        'ada' => true,
                        'asensitive' => true,
                        'assignment' => true,
                        'asymmetric' => true,
                        'atomic' => true,
                        'avg' => true,
                        'between' => true,
                        'bitvar' => true,
                        'bit_length' => true,
                        'c' => true,
                        'called' => true,
                        'cardinality' => true,
                        'catalog_name' => true,
                        'chain' => true,
                        'character_length' => true,
                        'character_set_catalog' => true,
                        'character_set_name' => true,
                        'character_set_schema' => true,
                        'char_length' => true,
                        'checked' => true,
                        'class_origin' => true,
                        'coalesce' => true,
                        'cobol' => true,
                        'collation_catalog' => true,
                        'collation_name' => true,
                        'collation_schema' => true,
                        'column_name' => true,
                        'command_function' => true,
                        'command_function_code' => true,
                        'committed' => true,
                        'condition_number' => true,
                        'connection_name' => true,
                        'constraint_catalog' => true,
                        'constraint_name' => true,
                        'constraint_schema' => true,
                        'contains' => true,
                        'convert' => true,
                        'count' => true,
                        'cursor_name' => true,
                        'datetime_interval_code' => true,
                        'datetime_interval_precision' => true,
                        'defined' => true,
                        'definer' => true,
                        'dispatch' => true,
                        'dynamic_function' => true,
                        'dynamic_function_code' => true,
                        'existing' => true,
                        'exists' => true,
                        'extract' => true,
                        'final' => true,
                        'fortran' => true,
                        'g' => true,
                        'generated' => true,
                        'granted' => true,
                        'hierarchy' => true,
                        'hold' => true,
                        'implementation' => true,
                        'infix' => true,
                        'insensitive' => true,
                        'instance' => true,
                        'instantiable' => true,
                        'invoker' => true,
                        'k' => true,
                        'key_member' => true,
                        'key_type' => true,
                        'length' => true,
                        'lower' => true,
                        'm' => true,
                        'max' => true,
                        'message_length' => true,
                        'message_octet_length' => true,
                        'message_text' => true,
                        'method' => true,
                        'min' => true,
                        'mod' => true,
                        'more' => true,
                        'mumps' => true,
                        'name' => true,
                        'nullable' => true,
                        'nullif' => true,
                        'number' => true,
                        'octet_length' => true,
                        'options' => true,
                        'overlaps' => true,
                        'overlay' => true,
                        'overriding' => true,
                        'parameter_mode' => true,
                        'parameter_name' => true,
                        'parameter_ordinal_position' => true,
                        'parameter_specific_catalog' => true,
                        'parameter_specific_name' => true,
                        'parameter_specific_schema' => true,
                        'pascal' => true,
                        'pli' => true,
                        'position' => true,
                        'repeatable' => true,
                        'returned_length' => true,
                        'returned_octet_length' => true,
                        'returned_sqlstate' => true,
                        'routine_catalog' => true,
                        'routine_name' => true,
                        'routine_schema' => true,
                        'row_count' => true,
                        'scale' => true,
                        'schema_name' => true,
                        'security' => true,
                        'self' => true,
                        'sensitive' => true,
                        'serializable' => true,
                        'server_name' => true,
                        'similar' => true,
                        'simple' => true,
                        'source' => true,
                        'specific_name' => true,
                        'style' => true,
                        'subclass_origin' => true,
                        'sublist' => true,
                        'substring' => true,
                        'sum' => true,
                        'symmetric' => true,
                        'system' => true,
                        'table_name' => true,
                        'transactions_committed' => true,
                        'transactions_rolled_back' => true,
                        'transaction_active' => true,
                        'transform' => true,
                        'transforms' => true,
                        'translate' => true,
                        'trigger_catalog' => true,
                        'trigger_name' => true,
                        'trigger_schema' => true,
                        'trim' => true,
                        'type' => true,
                        'uncommitted' => true,
                        'unnamed' => true,
                        'upper' => true,
                        'user_defined_type_catalog' => true,
                        'user_defined_type_name' => true,
                        'user_defined_type_schema' => true,
                    ),
                ),
            ),
            'blocks' => 
            array (
                'qidentifier' => 
                array (
                    'name' => 'qidentifier',
                    'case' => false,
                    'innerGroup' => 'identifier',
                    'delimGroup' => 'quotes',
                    'start' => '/`/i',
                    'end' => '/`/i',
                    'remember' => false,
                    'type' => 'region',
                    'order' => 0,
                ),
                'mlcomment' => 
                array (
                    'name' => 'mlcomment',
                    'case' => false,
                    'innerGroup' => 'comment',
                    'delimGroup' => 'comment',
                    'start' => '/\\/\\*/i',
                    'end' => '/\\*\\//i',
                    'remember' => false,
                    'type' => 'region',
                    'order' => 1,
                ),
                'comment' => 
                array (
                    'name' => 'comment',
                    'case' => false,
                    'innerGroup' => 'comment',
                    'match' => '/(#|--\\s).*/i',
                    'multiline' => false,
                    'type' => 'block',
                    'order' => 2,
                ),
                'identifier' => 
                array (
                    'name' => 'identifier',
                    'case' => false,
                    'innerGroup' => 'identifier',
                    'match' => '/[a-z_]\\w*/i',
                    'multiline' => false,
                    'type' => 'block',
                    'order' => 3,
                ),
                'strdouble' => 
                array (
                    'name' => 'strdouble',
                    'case' => false,
                    'innerGroup' => 'string',
                    'delimGroup' => 'quotes',
                    'start' => '/"/i',
                    'end' => '/"/i',
                    'remember' => false,
                    'type' => 'region',
                    'order' => 4,
                    'lookfor' => 
                    array (
                        0 => 'escaped',
                    ),
                ),
                'brackets' => 
                array (
                    'name' => 'brackets',
                    'case' => false,
                    'innerGroup' => 'code',
                    'delimGroup' => 'brackets',
                    'start' => '/\\(/i',
                    'end' => '/\\)/i',
                    'remember' => false,
                    'type' => 'region',
                    'order' => 5,
                    'lookfor' => 
                    array (
                        0 => 'qidentifier',
                        1 => 'mlcomment',
                        2 => 'comment',
                        3 => 'identifier',
                        4 => 'strdouble',
                        5 => 'brackets',
                        6 => 'strsingle',
                        7 => 'exponent',
                        8 => 'float',
                        9 => 'integer',
                        10 => 'hexinteger',
                    ),
                ),
                'strsingle' => 
                array (
                    'name' => 'strsingle',
                    'case' => false,
                    'innerGroup' => 'string',
                    'delimGroup' => 'quotes',
                    'start' => '/\'/i',
                    'end' => '/\'/i',
                    'remember' => false,
                    'type' => 'region',
                    'order' => 6,
                    'lookfor' => 
                    array (
                        0 => 'escaped',
                    ),
                ),
                'escaped' => 
                array (
                    'name' => 'escaped',
                    'case' => false,
                    'innerGroup' => 'special',
                    'match' => '/\\\\./i',
                    'multiline' => false,
                    'type' => 'block',
                    'order' => 7,
                ),
                'exponent' => 
                array (
                    'name' => 'exponent',
                    'case' => false,
                    'innerGroup' => 'number',
                    'match' => '/((\\d+|((\\d*\\.\\d+)|(\\d+\\.\\d*)))[eE][+-]?\\d+)/i',
                    'multiline' => false,
                    'type' => 'block',
                    'order' => 8,
                ),
                'float' => 
                array (
                    'name' => 'float',
                    'case' => false,
                    'innerGroup' => 'number',
                    'match' => '/(\\d*\\.\\d+)|(\\d+\\.\\d*)/i',
                    'multiline' => false,
                    'type' => 'block',
                    'order' => 9,
                ),
                'integer' => 
                array (
                    'name' => 'integer',
                    'case' => false,
                    'innerGroup' => 'number',
                    'match' => '/\\d+l?|\\b0l?\\b/i',
                    'multiline' => false,
                    'type' => 'block',
                    'order' => 10,
                ),
                'hexinteger' => 
                array (
                    'name' => 'hexinteger',
                    'case' => false,
                    'innerGroup' => 'number',
                    'match' => '/0[xX][\\da-f]+l?/i',
                    'multiline' => false,
                    'type' => 'block',
                    'order' => 11,
                ),
            ),
            'toplevel' => 
            array (
                0 => 'qidentifier',
                1 => 'mlcomment',
                2 => 'comment',
                3 => 'identifier',
                4 => 'strdouble',
                5 => 'brackets',
                6 => 'strsingle',
                7 => 'exponent',
                8 => 'float',
                9 => 'integer',
                10 => 'hexinteger',
            ),
            'case' => false,
            'defClass' => 'code',
        );

        $this->_options = $options;
    }
}

?>